[package]
name = "skiplist-rust"
version = "0.1.0"
edition = "2021"
license = "MIT"
keywords = ["data-structure", "unsafe", "lockless"]
authors = ["Simon Liu"]
documentation = "readme.md"
description = "A lockless skiplist implementation in Rust"

[dependencies]
rand = "0.8.5"
